$color = rgba(50, 48, 47, 1)
$inner_color = rgba(50, 48, 47, 0.66)
$outer_color = rgba(177, 98, 134, 1)
$font_color = rgba(235, 219, 178, 1)
$placeholder_color = rgba(235, 219, 178, 0.7)
$check_color = rgba(104, 157, 106, 1)
